CREATE TABLE LOGS (
    logid		BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    class		VARCHAR(200) DEFAULT NULL,
    method		VARCHAR(100) DEFAULT NULL,
    createtime 	DATETIME DEFAULT NULL,
    loglevel	VARCHAR(50) DEFAULT NULL,
    msg 		VARCHAR(4000) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;